#server.port = 8090

server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_study_02
    username: root
    password: 1111

mybatis:
  mapper-locations:
    - /mappers/*.xml

